### ISSUE TITLE
Link to Newick tree for sc2 dataset is broken

### ISSUE THREAD

**Issue by batson** [globalmicrobialidentifier-WG3/datasets#3]
Hello! The link

https://itol.embl.de/download.cgi?f=xgkDfgJpj0-D75secf5tHA_newick.txt

from [sarscov2-SNF-A.tsv](https://github.com/globalmicrobialidentifier-WG3/datasets/blob/master/datasets/sarscov2-SNF-A.tsv) appears to be broken.

**Comment by lskatz** [comment]
You're right!  I don't have time to debug just yet but here it is online: https://itol.embl.de/shared/lskatz (click on "tree.nwk").

Thanks for reporting it!

**Comment by lskatz** [comment]
PS I am totally open to a pull request if anyone wants to place the tree file into the trees subdirectory and fix the URL to point to it.  I just don't have the time anymore.

Steps:

1. put the newick file into https://github.com/globalmicrobialidentifier-WG3/datasets/tree/master/datasets/trees/sarscov2-SNF-A.dnd
2. update the URL in the spreadsheet to point to https://github.com/globalmicrobialidentifier-WG3/datasets/tree/master/datasets/trees/sarscov2-SNF-A.dnd

**Comment by lskatz** [comment]
Fixed in c93d361..e7567f8
